openapi: 3.0.3

info:
  title: Бизнес логика
  description: Пародия бизнес процесса загрузки видео и потребления контента c сайта https://rutube.ru
  version: 1.0.0

components:
  schemas:
    sourceId:
      type: string
      format: uuid
      description: Идентификатор контента
      example: "4153ca20-a15d-478e-9427-875f95c677f8"

    uploadLink:
      type: string
      description: Ссылка для загрузки (PUT по ссылке)
      example: "https://example.site/upload/link"

    downloadLink:
      type: string
      description: Ссылка для загрузки (GET по ссылке)
      example: "https://example.site/download/link"

    title:
      type: string
      maxLength: 100
      description: Название
      example: "НЕПРИМЕЧАТЕЛЬНОЕ название"

    description:
      type: string
      maxLength: 5000
      description: Описание
      example: "ставьте лайки пж"


    category:
      type: string
      description: Категория
      enum:
        - "ANIME"
        - "FOOD"
        - "MUSIC"
        - "SCIENCE"
        - "HUMOUR"

    access:
      type: string
      description: Параметр доступа
      enum:
        - "PUBLIC"
        - "LINK"
        - "PRIVATE"

    ageRestriction:
      type: boolean
      description: Флаг наличия возрастного ограничения 18+

    comments:
      type: boolean
      description: Флаг отключения комментариев

    publishedAt:
      type: integer
      format: int64
      description: Время публикации
      example: 1709064700772

    status:
      type: string
      description: Статус
      enum:
        - "UPLOAD_PENDING"
        - "MODERATION_PENDING"
        - "MODERATION_FAILED"
        - "FILL_PENDING"
        - "READY"
        - "PUBLISHED"

    commentId:
      type: string
      format: uuid
      description: Идентификатор комментария
      example: "17c70255-2c5b-43f8-bc58-69f04af16cc5"

    content:
      type: string
      maxLength: 200
      description: Содержание
      example: "хрень переделывай"

    replies:
      type: integer
      description: Количество ответов
      example: 5

    author:
      type: string
      description: Автор
      example: "cup_of_code"

    reaction:
      type: string
      description: Тип реакции
      enum:
        - "LIKE"
        - "DISLIKE"

    result:
      type: string
      description: Результат модерации
      enum:
        - "SUCCESS"
        - "FAILURE"

    comment:
      type: string
      description: Комментарий
      example: "присутствуют сцены насилия"

    pageNumber:
      type: integer
      format: int32
      description: Номер страницы (параметр пагинации)
      default: 0

    pageSize:
      type: integer
      format: int32
      maximum: 100
      description: Размер страницы (параметр пагинации)
      default: 1

    file:
      type: string
      format: binary
      description: Файл

    NewVideoResponse:
      type: object
      properties:
        sourceId:
          $ref: "#/components/schemas/sourceId"
        uploadLink:
          $ref: "#/components/schemas/uploadLink"

    VideoThumbInfo:
      type: object
      properties:
        videoId:
          $ref: "#/components/schemas/sourceId"
        author:
          $ref: "#/components/schemas/author"
        title:
          $ref: "#/components/schemas/title"
        category:
          $ref: "#/components/schemas/category"
        publishedAt:
          $ref: "#/components/schemas/publishedAt"

    GetVideosResponse:
      type: object
      properties:
        videos:
          type: array
          items:
            $ref: "#/components/schemas/VideoThumbInfo"

    GetVideoResponse:
      type: object
      properties:
        downloadLink:
          $ref: "#/components/schemas/downloadLink"
        author:
          $ref: "#/components/schemas/author"
        title:
          $ref: "#/components/schemas/title"
        description:
          $ref: "#/components/schemas/description"
        category:
          $ref: "#/components/schemas/category"
        ageRestriction:
          $ref: "#/components/schemas/ageRestriction"
        comments:
          $ref: "#/components/schemas/comments"
        publishedAt:
          $ref: "#/components/schemas/publishedAt"

    PutVideoRequest:
      type: object
      properties:
        title:
          $ref: "#/components/schemas/title"
        description:
          $ref: "#/components/schemas/description"
        category:
          $ref: "#/components/schemas/category"
        access:
          $ref: "#/components/schemas/access"
        ageRestriction:
          $ref: "#/components/schemas/ageRestriction"
        comments:
          $ref: "#/components/schemas/comments"

    GetVideoStatusResponse:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/status"
        comment:
          $ref: "#/components/schemas/comment"

    CreateCommentRequest:
      type: object
      properties:
        sourceId:
          $ref: "#/components/schemas/sourceId"
        parentId:
          $ref: "#/components/schemas/commentId"
        content:
          $ref: "#/components/schemas/content"

    CommentInfo:
      type: object
      properties:
        commentId:
          $ref: "#/components/schemas/commentId"
        author:
          $ref: "#/components/schemas/author"
        content:
          $ref: "#/components/schemas/content"
        replies:
          $ref: "#/components/schemas/replies"

    GetCommentsResponse:
      type: object
      properties:
        comments:
          type: array
          items:
            $ref: "#/components/schemas/CommentInfo"

    CreateReactionRequest:
      type: object
      properties:
        sourceId:
          $ref: "#/components/schemas/sourceId"
        reaction:
          $ref: "#/components/schemas/reaction"

    ReactionInfo:
      type: object
      properties:
        reaction:
          $ref: "#/components/schemas/reaction"
        count:
          type: integer
          format: int64

    GetReactionsResponse:
      type: object
      properties:
        reactions:
          type: array
          items:
            $ref: "#/components/schemas/ReactionInfo"

    GetMyReactionResponse:
      type: object
      properties:
        reaction:
          $ref: "#/components/schemas/reaction"

    GetNextModerationResponse:
      type: object
      properties:
        sourceId:
          $ref: "#/components/schemas/sourceId"
        downloadLink:
          $ref: "#/components/schemas/downloadLink"

    UploadModerationResultRequest:
      type: object
      properties:
        sourceId:
          $ref: "#/components/schemas/sourceId"
        result:
          $ref: "#/components/schemas/result"
        comment:
          $ref: "#/components/schemas/comment"

    PutSourceRequest:
      type: object
      properties:
        file:
          $ref: "#/components/schemas/file"


paths:
  # https://cloud.google.com/apis/design/custom_methods
  # https://cloud.yandex.ru/ru/docs/compute/api-ref/
  # https://cloud.google.com/identity-platform/docs/use-rest-api
  /api/videos:new:
    post:
      summary: Инициация создания нового видео
      tags:
        - video
      parameters:
        - in: query
          name: prototype
          description: Прототип, на основе которого заполняться данные нового видео
          schema:
            $ref: "#/components/schemas/sourceId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewVideoResponse"
        401:
          description: UNAUTHORIZED
        404:
          description: NOT FOUND

  /api/videos:
    get:
      summary: Получение опубликованных видео
      tags:
        - video
      parameters:
        - in: query
          name: pageNumber
          description: Номер страницы (параметр пагинации)
          schema:
            $ref: "#/components/schemas/pageNumber"
        - in: query
          name: pageSize
          description: Размер страницы (параметр пагинации)
          schema:
            $ref: "#/components/schemas/pageSize"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetVideosResponse"
        400:
          description: BAD REQUEST

  /api/videos/{sourceId}:
    get:
      summary: Получение подробной информации об опубликованном видео
      tags:
        - video
      parameters:
        - in: path
          name: sourceId
          description: Идентификатор видео (контента)
          required: true
          schema:
            $ref: "#/components/schemas/sourceId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetVideoResponse"
        404:
          description: NOT FOUND

    put:
      summary: Заполнение данных о видео
      tags:
        - video
      parameters:
        - in: path
          name: sourceId
          description: Идентификатор видео (контента)
          required: true
          schema:
            $ref: "#/components/schemas/sourceId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutVideoRequest"
      responses:
        200:
          description: OK
        400:
          description: BAD REQUEST
        401:
          description: UNAUTHORIZED
        404:
          description: NOT FOUND

  /api/videos/{sourceId}/status:
    get:
      summary: Получение информации о статусе видео
      tags:
        - video
      parameters:
        - in: path
          name: sourceId
          description: Идентификатор видео (контента)
          required: true
          schema:
            $ref: "#/components/schemas/sourceId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetVideoStatusResponse"
        401:
          description: UNAUTHORIZED
        404:
          description: NOT FOUND

  /api/videos/{sourceId}:publish:
    post:
      summary: Публикация видео
      tags:
        - video
      parameters:
        - in: path
          name: sourceId
          description: Идентификатор видео (контента)
          required: true
          schema:
            $ref: "#/components/schemas/sourceId"
      responses:
        200:
          description: OK
        401:
          description: UNAUTHORIZED
        404:
          description: NOT FOUND
        409:
          description: CONFLICT

  /api/comments:
    post:
      summary: Создание комментария на контент
      tags:
        - comment
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCommentRequest"
      responses:
        200:
          description: OK
        400:
          description: BAD REQUEST
        401:
          description: UNAUTHORIZED
        404:
          description: NOT FOUND
        409:
          description: CONFLICT

    get:
      summary: Получение комментариев под контентом
      tags:
        - comment
      parameters:
        - in: query
          name: sourceId
          description: Идентификатор контента
          required: true
          schema:
            $ref: "#/components/schemas/sourceId"
        - in: query
          name: parentId
          description: Идентификатор родительского комментария
          schema:
            $ref: "#/components/schemas/commentId"
        - in: query
          name: pageNumber
          description: Номер страницы (параметр пагинации)
          schema:
            $ref: "#/components/schemas/pageNumber"
        - in: query
          name: pageSize
          description: Размер страницы (параметр пагинации)
          schema:
            $ref: "#/components/schemas/pageSize"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetCommentsResponse"
        400:
          description: BAD REQUEST
        404:
          description: NOT FOUND
        409:
          description: CONFLICT

  /api/reactions:
    post:
      summary: Создание реакции на контент
      tags:
        - reaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReactionRequest"
      responses:
        200:
          description: OK
        400:
          description: BAD REQUEST
        401:
          description: UNAUTHORIZED
        404:
          description: NOT FOUND

    get:
      summary: Получение реакций под контентом
      tags:
        - reaction
      parameters:
        - in: query
          name: sourceId
          description: Идентификатор контента
          required: true
          schema:
            $ref: "#/components/schemas/sourceId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetReactionsResponse"
        400:
          description: BAD REQUEST
        401:
          description: UNAUTHORIZED
        404:
          description: NOT FOUND

  /api/reactions/my:
    get:
      summary: Получение реакции пользователя под контентом
      tags:
        - reaction
      parameters:
        - in: query
          name: sourceId
          description: Идентификатор контента
          required: true
          schema:
            $ref: "#/components/schemas/sourceId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetMyReactionResponse"
        400:
          description: BAD REQUEST
        401:
          description: UNAUTHORIZED
        404:
          description: NOT FOUND

  /api/moderation/next:
    get:
      summary: Получение следующего контента для модерации
      tags:
        - moderation
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetNextModerationResponse"
        401:
          description: UNAUTHORIZED
        403:
          description: FORBIDDEN

  /api/moderation:
    post:
      summary: Загрузка результата модерации
      tags:
        - moderation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadModerationResultRequest"
      responses:
        200:
          description: OK
        400:
          description: BAD REQUEST
        401:
          description: UNAUTHORIZED
        403:
          description: FORBIDDEN
        404:
          description: NOT FOUND

  /api/source/{sourceId}:
    put:
      summary: Загрузка ресурса
      tags:
        - source
      parameters:
        - in: path
          name: sourceId
          description: Идентификатор ресурса
          required: true
          schema:
            $ref: "#/components/schemas/sourceId"
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/PutSourceRequest"
      responses:
        200:
          description: OK
        400:
          description: BAD REQUEST
        401:
          description: UNAUTHORIZED
        404:
          description: NOT FOUND
        409:
          description: CONFLICT
        413:
          description: REQUEST ENTITY TOO LARGE

    get:
      summary: Загрузка ресурса
      tags:
        - source
      parameters:
        - in: path
          name: sourceId
          description: Идентификатор ресурса
          required: true
          schema:
            $ref: "#/components/schemas/sourceId"
      responses:
        200:
          description: OK
          content:
            video/mp4:
              schema:
                $ref: "#/components/schemas/file"
        404:
          description: NOT FOUND
